// GENERATED by tool/import_tobymao_title.dart: the titles in this
// folder, for GameTitle.all. Importing a title rewrites it, as does
// `dart run tool/import_tobymao_title.dart --registry`.

import 'title_1807.dart';
import 'title_1844.dart';
import 'title_1854.dart';
import 'title_1880.dart';
import 'title_1889.dart';
import 'title_data.dart';

const List<TitleData> importedTitles = [
  title1807,
  title1844,
  title1854,
  title1880,
  title1889,
];
